services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  postgres:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/18/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  service:
    build: .
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=${SERVICE_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_INITDB_DATABASE}?authSource=admin
      - POSTGRES_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

volumes:
  db_data:
  mongo_data:
